import Layout from "./component/Layout";
import { useState, useEffect } from "react";
import { BsSend } from "react-icons/bs";
import { AiOutlineAudio } from "react-icons/ai";
import ScrollToBottom from "react-scroll-to-bottom";
import axios from "axios";
import TypeWriterEffect from "react-typewriter-effect";

function App() {
  const [messages, setMessages] = useState([]);
  const [userMessage, setUserMessage] = useState("");

  const handleUserMessageChange = (e) => {
    setUserMessage(e.target.value);
  };

  const sendMessage = async (e) => {
    e.preventDefault();

    const msg = { user: userMessage, bot: "" };
    setMessages([...messages, msg]);
    setUserMessage("");

    try {
      const response = await axios.post(
        "https://intellisquadai-production.up.railway.app/chat/",
        { text: userMessage }
      );
      console.log(response.data.result);

      if (response.data) {
        setMessages([
          ...messages,
          { user: userMessage, bot: response.data.result },
        ]);
      }
    } catch (error) {
      console.error(error);
    }
  };
  return (
    <>
      <Layout>
        <section className="mt-[80px">
          <h1 className="text-3xl font-bold underline">Hello world!</h1>
          <ScrollToBottom className="flex-1 overflow-y-scroll">
            {messages.map((message, index) => (
              <div key={index} className="mb-2">
                <div className="flex justify-end max-w-[3/5] min-w-[2rem]">
                  <div className="rounded py-2 px-3 bg-blue-500 text-white  my-[0.5rem]">
                    {message.user}
                  </div>
                </div>
                <div className="flex max-w-[80%] min-w-[2rem]">
                  {message.bot && (
                    <div className="rounded py-2 px-3 bg-green-500 text-white  my-[0.5rem]">
                      <TypeWriterEffect
                        textStyle={{ fontFamily: "Red Hat Display" }}
                        startDelay={100}
                        cursorColor="white"
                        text={message.bot}
                        typeSpeed={100}
                        //scrollArea={myAppRef}
                      />
                    </div>
                  )}
                </div>
              </div>
            ))}
          </ScrollToBottom>

          <div className="fixed bottom-0 md:w-[70%] w-[90%] my-[20px] rounded-md bg-[purple] text-center">
            <form action="" onSubmit={sendMessage}>
              <aside className="w-full rounded-md bg-white border-[1px] border-[purple] flex items-center ">
                <textarea
                  name=""
                  id=""
                  className="w-[95%] p-[0.2rem] outline-none "
                  value={userMessage}
                  onChange={handleUserMessageChange}
                ></textarea>
                <button type="submit">
                  <BsSend className="text-2xl mx-[0.5rem]" />
                </button>
                <AiOutlineAudio className="text-2xl" />
              </aside>
            </form>
            <p className="text-white">
              {" "}
              all results are generated by AI, if you are getting any issues{" "}
              <a href="#">report here</a>
            </p>
          </div>
        </section>
      </Layout>
    </>
  );
}

export default App;
